### ISSUE TITLE
The module cause Google Photos editor not working

### ISSUE THREAD

**Issue by ralph950412** [Pixel-Props/pixel.features#2]
Version: 5.67.0.409448818 (Installed from play store)
Screen recording here: https://photos.app.goo.gl/diVzxLMrAvb6QWSc7
Disable this module made it works again.

**Comment by 0x11DFE** [comment]
What option's have you selected while flashing?

**Comment by utajum** [comment]
Same here, used the last props zip that was AIO, before it was split.
If you crop a picture, two or tree times, google photos freezes and needs to be force stopped

**Comment by 0x11DFE** [comment]
I'm using GPhoto 5.68.0.410913581 and running without any issues.

**Comment by ralph950412** [comment]
> I'm using GPhoto 5.68.0.410913581 and running without any issues.

I'm using that version too, but the problem still exists

**Comment by 0x11DFE** [comment]
> > I'm using GPhoto 5.68.0.410913581 and running without any issues.
> 
> I'm using that version too, but the problem still exists

Then i doubt it has anything to do with the module.
Could you provide some kind of logs?

**Comment by 0x11DFE** [comment]
Closing until response.
