### ISSUE TITLE
Bootloop on A11

### ISSUE THREAD

**Issue by Apriljoke** [Pixel-Props/pixel.features#3]
Latest update causes bootloop on A11, LOS.
Chose only to remove XML,  even without sailfish props.

**Comment by 0x11DFE** [comment]
> Latest update causes bootloop on A11, LOS. Chose only to remove XML, even without sailfish props.

Could you send over logs from /data/adb/modules/Pixel_Features/service.log ?

**Comment by Apriljoke** [comment]
[service.log](https://github.com/Pixel-Props/pixel.features/files/8153316/service.log)
 
It's quite empty...
What more can I provide?

**Comment by 0x11DFE** [comment]
> [service.log](https://github.com/Pixel-Props/pixel.features/files/8153316/service.log)
> 
> It's quite empty... What more can I provide?

Then i cannot seem to figure why it could bootloop, Could you uninstall the module and after reboot reinstall it and save the magisk logs on the top right corner and hand it over here please.

**Comment by Apriljoke** [comment]
[magisk_install_log_2022-02-28T13_47_55.log](https://github.com/Pixel-Props/pixel.features/files/8153410/magisk_install_log_2022-02-28T13_47_55.log)

Logs.

Strange because previous versions was working like a charm

**Comment by 0x11DFE** [comment]
> [magisk_install_log_2022-02-28T13_47_55.log](https://github.com/Pixel-Props/pixel.features/files/8153410/magisk_install_log_2022-02-28T13_47_55.log)
> 
> Logs.
> 
> Strange because previous versions was working like a charm

Can you try removing the service.sh from your module?

**Comment by Apriljoke** [comment]
Still bootloop :(

**Comment by 0x11DFE** [comment]
> Still bootloop :(

What is your Magisk version?

**Comment by Apriljoke** [comment]
Latest (24102)

**Comment by 0x11DFE** [comment]
Can you also try removing sepolicy.rule?

**Comment by Apriljoke** [comment]
Tried and it didn't help

**Comment by 0x11DFE** [comment]
Did you try removing system/product/framework/com.google.android.dialer.support.jar from the module?
If not, try removing things until it gets fixed, then let me know.
Only remove content from the system in the module.

**Comment by Apriljoke** [comment]
I tried but it didn't help.  
But I find a way to boot - deleting folder permissions on system/product

**Comment by 0x11DFE** [comment]
> I tried but it didn't help. But I find a way to boot - deleting folder permissions on system/product

Then the problem is in that folder keep searching within that folder for a file that could be causing the problem.

**Comment by Apriljoke** [comment]
Finally, I got some time to check it.
It's the file privapp-permisions-google-p.xml causing the bootloop

**Comment by 0x11DFE** [comment]
> Finally, I got some time to check it. It's the file privapp-permisions-google-p.xml causing the bootloop

Can you try the latest release ([22030300](https://github.com/Pixel-Props/pixel.features/releases/tag/22030300))?

**Comment by Apriljoke** [comment]
Yes.
It's working 👍
